SUPABASE_URL = "https://oxekkilbifeicbrqvbue.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZWtraWxiaWZlaWNicnF2YnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQ2MDM1NDcsImV4cCI6MjA0MDE3OTU0N30.2_KMELwEcpWj2q6WWJh92qWMk0aREIysbOTBDM1iwlc"
GOOGLE_CLIENT_ID = "647775398332-gq8t0dkgs4u4pe18anbftm65dkojj9hl.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GEMINI_API = "AIzaSyC8QK1LuKtLdaCHM8cDj-Rttu1sNJ_J69s"